INSERT INTO LANGUAGES (ID, NAME, LAST_UPDATE) VALUES (1, 'English', CURRENT_TIMESTAMP);
INSERT INTO LANGUAGES (ID, NAME, LAST_UPDATE) VALUES (2, 'Spanish', CURRENT_TIMESTAMP);
INSERT INTO LANGUAGES (ID, NAME, LAST_UPDATE) VALUES (3, 'German', CURRENT_TIMESTAMP);

INSERT INTO ANSWERS (ID, ID_CATEGORY, DESCRIPTION, LAST_UPDATE) VALUES (1, 1, 'gets', CURRENT_TIMESTAMP);
INSERT INTO ANSWERS (ID, ID_CATEGORY, DESCRIPTION, LAST_UPDATE) VALUES (2, 1, 'studies', CURRENT_TIMESTAMP);
INSERT INTO ANSWERS (ID, ID_CATEGORY, DESCRIPTION, LAST_UPDATE) VALUES (3, 1, 'go', CURRENT_TIMESTAMP);
INSERT INTO ANSWERS (ID, ID_CATEGORY, DESCRIPTION, LAST_UPDATE) VALUES (4, 1, 'practices', CURRENT_TIMESTAMP);
INSERT INTO ANSWERS (ID, ID_CATEGORY, DESCRIPTION, LAST_UPDATE) VALUES (5, 1, 'speak', CURRENT_TIMESTAMP);
INSERT INTO ANSWERS (ID, ID_CATEGORY, DESCRIPTION, LAST_UPDATE) VALUES (6, 1, 'cooks', CURRENT_TIMESTAMP);
INSERT INTO ANSWERS (ID, ID_CATEGORY, DESCRIPTION, LAST_UPDATE) VALUES (7, 1, 'pay', CURRENT_TIMESTAMP);
INSERT INTO ANSWERS (ID, ID_CATEGORY, DESCRIPTION, LAST_UPDATE) VALUES (8, 1, 'sleeps', CURRENT_TIMESTAMP);
INSERT INTO ANSWERS (ID, ID_CATEGORY, DESCRIPTION, LAST_UPDATE) VALUES (9, 1, 'work', CURRENT_TIMESTAMP);
INSERT INTO ANSWERS (ID, ID_CATEGORY, DESCRIPTION, LAST_UPDATE) VALUES (10, 1, 'have', CURRENT_TIMESTAMP);

INSERT INTO EXERCISES (DESCRIPTION, USER_ID, LAST_UPDATE) VALUES ('Exercise 1', 'JESC007', CURRENT_TIMESTAMP);
INSERT INTO EXERCISES (DESCRIPTION, USER_ID, LAST_UPDATE) VALUES ('Exercise 2', 'JESC007', CURRENT_TIMESTAMP);

INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 1, 'He ', 'gets', ' up at 7 a.m. every day. (get)',  '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 1, 'My sister ', 'studies', ' a lot for her exams. (study)', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 1, 'My parents and I ', 'go', ' to the cinema on weekends. (go)', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 1, 'My daughter ', 'practices', ' soccer in the park every afternoon. (practice)', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 1, 'Does Paul ', 'speak', ' German fluently? (speak)', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 1, 'My father ', 'cooks', ' delicious meals for the family. (cook)', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 1, 'The teachers ', 'pay', ' attention in class. (pay)', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 1, 'The donkey always ', 'sleeps', ' on the sofa in the afternoon. (sleep)', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 1, 'Did you ', 'work', ' in the office everyday? (work)', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 1, 'Everyday I ', 'have', ' cereal with milk. (have)', '', CURRENT_TIMESTAMP);

INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 2, 'Martha is 2 meters ', 'tall', ' and is 30 years old.', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 2, 'She is ', 'running', ' in the park right now.', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 2, 'The last time I ', 'went', ' to the city was yesterday.', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 2, 'There is a ', 'small', ' cabin near by the river.', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 2, 'That is the ', 'best', ' city of the world.', '', CURRENT_TIMESTAMP);

INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 3, 'Bugaboo wants to:', 'help', '', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 3, 'Bugaboo is:', 'a witch', '', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 3, 'The man is worried about:', 'the future of many animals', '', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 3, 'What airports really need is:', 'an entertainment area so people can kill time', '', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 3, 'The greatest pleasure of the man is:', 'watching them grow up', '', '', CURRENT_TIMESTAMP);
INSERT INTO QUESTIONS (ID_EXERCISE, ID_CATEGORY, DESCRIPTION1, ANSWER, DESCRIPTION2, URL_FILE_NAME, LAST_UPDATE) VALUES (1, 4, 'This record is used to get reading image file name', null, null, 'three_little_pigs.jpg', CURRENT_TIMESTAMP);

INSERT INTO CATEGORIES (ID, NAME, LAST_UPDATE) VALUES (1, 'Form with 1 text field answer', CURRENT_TIMESTAMP);
INSERT INTO CATEGORIES (ID, NAME, LAST_UPDATE) VALUES (2, 'Form with combo-box answer (3 options)', CURRENT_TIMESTAMP);
INSERT INTO CATEGORIES (ID, NAME, LAST_UPDATE) VALUES (3, 'Text Audio recording', CURRENT_TIMESTAMP);
INSERT INTO CATEGORIES (ID, NAME, LAST_UPDATE) VALUES (4, 'Picture for reading section', CURRENT_TIMESTAMP);

INSERT INTO COMBO_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (1, 2, 11, 'tall', CURRENT_TIMESTAMP);
INSERT INTO COMBO_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (2, 2, 11, 'long', CURRENT_TIMESTAMP);
INSERT INTO COMBO_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (3, 2, 11, 'high', CURRENT_TIMESTAMP);
INSERT INTO COMBO_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (4, 2, 12, 'running', CURRENT_TIMESTAMP);
INSERT INTO COMBO_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (5, 2, 12, 'runs', CURRENT_TIMESTAMP);
INSERT INTO COMBO_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (6, 2, 12, 'run', CURRENT_TIMESTAMP);
INSERT INTO COMBO_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (7, 2, 13, 'went', CURRENT_TIMESTAMP);
INSERT INTO COMBO_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (8, 2, 13, 'gone', CURRENT_TIMESTAMP);
INSERT INTO COMBO_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (9, 2, 13, 'go', CURRENT_TIMESTAMP);
INSERT INTO COMBO_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (10, 2, 14, 'small', CURRENT_TIMESTAMP);
INSERT INTO COMBO_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (11, 2, 14, 'little', CURRENT_TIMESTAMP);
INSERT INTO COMBO_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (12, 2, 14, 'short', CURRENT_TIMESTAMP);
INSERT INTO COMBO_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (13, 2, 15, 'best', CURRENT_TIMESTAMP);
INSERT INTO COMBO_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (14, 2, 15, 'bet', CURRENT_TIMESTAMP);
INSERT INTO COMBO_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (15, 2, 15, 'better', CURRENT_TIMESTAMP);

INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (1, 3, 16, 'help', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (2, 3, 16, 'flee', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (3, 3, 16, 'sleep', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (4, 3, 16, 'cook', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (5, 3, 17, 'a witch', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (6, 3, 17, 'a child', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (7, 3, 17, 'a cat', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (8, 3, 17, 'a girl', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (9, 3, 18, 'the future of many animals', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (10, 3, 18, 'watching the animals walk around', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (11, 3, 18, 'going to a safari to Tanzania', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (12, 3, 18, 'going to the zoo', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (13, 3, 19, 'an entertainment area so people can kill time', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (14, 3, 19, 'people from all over the world', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (15, 3, 19, 'small towns', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (16, 3, 19, 'people crying with joy', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (17, 3, 20, 'watching them grow up', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (18, 3, 20, 'that his children are angels', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (19, 3, 20, 'that everything they say makes him smile', CURRENT_TIMESTAMP);
INSERT INTO CHECK_BOX_OPTION (ID, ID_CATEGORY, ID_QUESTION, DESCRIPTION, LAST_UPDATE) VALUES (20, 3, 20, 'that they have brought him endless amounts of joy', CURRENT_TIMESTAMP);

INSERT INTO SPEAKINGS (ID, NAME, DESCRIPTION, MEETING_TIME, MEETING_LINK, INFORMATION_VIDEO, USER_ID, LAST_UPDATE) VALUES (1, 'Deutsche Satzstrukturen', 'Basic introduction to Superstructure in German', '18:00', 'https://meet.google.com/dzh-rytd-prd', 'https://www.youtube.com/embed/icCQkBxydGU?autoplay=1&mute=1', 'JESC123', CURRENT_TIMESTAMP);
INSERT INTO SPEAKINGS (ID, NAME, DESCRIPTION, MEETING_TIME, MEETING_LINK, INFORMATION_VIDEO, USER_ID, LAST_UPDATE) VALUES (2, 'Third conditional', 'Basic introduction to third conditional in English', '20:00', 'https://meet.google.com/dzh-rytd-prd', 'https://www.youtube.com/embed/xwOCqtaZDrk?autoplay=1&mute=1', 'JESC123', CURRENT_TIMESTAMP);
